Forecasting Competition 
Spring 2026
Author: Bella Huang & Yeeun Kim

GitHub repository: https://github.com/BellaHuang03/KimHuang_ENV797_TSA_ForecastCompetition_S26

1. Set up
```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(lubridate)
library(forecast)
library(smooth)
library(ggplot2)
library(tidyverse)
```

2. Import datasets
```{r}
#Load Data
temp_raw <- read_excel("temperature.xlsx")
humid_raw   <- read_excel("relative_humidity.xlsx")
load_raw <- read_excel("load.xlsx")
```

3. Data Wrangling
```{r}
# Load Daily
load_daily <- load_raw %>%
  select(-meter_id) %>%                    
  rowwise() %>%
  mutate(daily_load = mean(c_across(h1:h24), na.rm = TRUE)) %>%
  ungroup() %>%
  select(date, daily_load) %>%
  mutate(date = as.Date(date))

# Temperature Daily
temp_daily <- temp_raw %>%
  mutate(date = as.Date(date)) %>%
  group_by(date) %>%
  summarise(daily_temp = mean(c_across(t_ws1:t_ws28), na.rm = TRUE))

# Humidity Daily
humid_daily <- humid_raw %>%
  mutate(date = as.Date(date)) %>%
  group_by(date) %>%
  summarise(daily_humid = mean(c_across(rh_ws1:rh_ws28), na.rm = TRUE))

# Daily Data
daily_data <- load_daily %>%
  left_join(temp_daily, by = "date") %>%
  left_join(humid_daily, by = "date")

head(daily_data)
nrow(daily_data) 
```

4. Exploratory Data Analysis
```{r}
# msts
ts_load <- msts(daily_data$daily_load, 
                seasonal.periods = c(7, 365.25),
                start = c(2005, 1))

# plots
autoplot(ts_load) +
  labs(title = "Daily Electricity Demand (2005–2011)",
       x = "Date", y = "Load (kWh)") +
  theme_bw()


# ACF & PACF
par(mfrow=c(1,2))
Acf(daily_data$daily_load, lag.max = 60, main = "ACF - Daily Demand")
Pacf(daily_data$daily_load, lag.max = 60, main = "PACF - Daily Demand")
```

5. Training and Test
```{r}
n_valid <- 31  

ts_train <- subset(ts_load, end = length(ts_load) - n_valid)
ts_valid <- subset(ts_load, start = length(ts_load) - n_valid + 1)

length(ts_train)
length(ts_valid) 

# Model 1: STL + ETS
fit_stl_ets <- stlf(ts_train, h = n_valid)
forecast_stl_ets <- forecast(fit_stl_ets, h = n_valid)

accuracy_stl_ets <- accuracy(forecast_stl_ets, ts_valid)
print(accuracy_stl_ets)

# Model 1 Plot
autoplot(forecast_stl_ets) +
  autolayer(ts_valid, series = "Actual") +
  labs(title = "Model 1: STL + ETS",
       x = "Date", y = "Demand") +
  theme_bw()

# Model 2: TBATS
fit_tbats <- tbats(ts_train)
forecast_tbats <- forecast(fit_tbats, h = n_valid)

accuracy_tbats <- accuracy(forecast_tbats, ts_valid)
print(accuracy_tbats)

# Model 2 Plot
autoplot(forecast_tbats) +
  autolayer(ts_valid, series = "Actual") +
  labs(title = "Model 2: TBATS",
       x = "Date", y = "Demand") +
  theme_bw()

# Model 3: Fourier + ARIMA
fourier_train <- fourier(ts_train, K = c(2, 4))
fourier_valid <- fourier(ts_train, K = c(2, 4), h = n_valid)

fit_fourier <- auto.arima(ts_train, 
                          xreg = fourier_train,
                          seasonal = FALSE,  
                          stepwise = FALSE,
                          approximation = FALSE)

forecast_fourier <- forecast(fit_fourier, 
                             xreg = fourier_valid,
                             h = n_valid)

accuracy_fourier <- accuracy(forecast_fourier, ts_valid)
print(accuracy_fourier)

# Model 3 Plot
autoplot(forecast_fourier) +
  autolayer(ts_valid, series = "Actual") +
  labs(title = "Model 3: Fourier + ARIMA",
       x = "Date", y = "Demand") +
  theme_bw()

# Model 4: NNETAR (Neural Network)
fit_nnetar <- nnetar(ts_train, P = 1, repeats = 20)
forecast_nnetar <- forecast(fit_nnetar, h = n_valid)

accuracy_nnetar <- accuracy(forecast_nnetar, ts_valid)
print(accuracy_nnetar)

# Model 4 Plot
autoplot(forecast_nnetar) +
  autolayer(ts_valid, series = "Actual") +
  labs(title = "Model 4: NNETAR",
       x = "Date", y = "Demand") +
  theme_bw()

# Model 5: STL + ARIMA
fit_stl_arima <- stlm(ts_train, 
                      s.window = "periodic",
                      method = "arima")

forecast_stl_arima <- forecast(fit_stl_arima, h = n_valid)

accuracy_stl_arima <- accuracy(forecast_stl_arima, ts_valid)
print(accuracy_stl_arima)

# Model 5 Plot
autoplot(forecast_stl_arima) +
  autolayer(ts_valid, series = "Actual") +
  labs(title = "Model 5: STL + ARIMA",
       x = "Date", y = "Demand") +
  theme_bw()
```

6. Forecast
```{r}
# Best Model: Fourier + ARIMA 
fourier_full <- fourier(ts_load, K = c(2, 4))
fourier_future <- fourier(ts_load, K = c(2, 4), h = 31)

fit_fourier_full <- auto.arima(ts_load,
                               xreg = fourier_full,
                               seasonal = FALSE,
                               stepwise = FALSE,
                               approximation = FALSE)

# Forecast: July 2011 
forecast_final <- forecast(fit_fourier_full,
                           xreg = fourier_future,
                           h = 31)

# Plot
autoplot(forecast_final) +
  labs(title = "Final Forecast: July 2011",
       x = "Date", y = "Demand") +
  theme_bw()
```

7. Add Temp and Humidity Data
--> Turned out the results are not the best
```{r}
# Add Temp and Humidity Data
xreg_train <- daily_data %>%
  slice(1:(nrow(daily_data) - n_valid)) %>%
  select(daily_temp, daily_humid) %>%
  as.matrix()

xreg_valid <- daily_data %>%
  slice((nrow(daily_data) - n_valid + 1):nrow(daily_data)) %>%
  select(daily_temp, daily_humid) %>%
  as.matrix()

nrow(xreg_train)
nrow(xreg_valid)

# Modeling: Fourier + ARIMA + Temp/Humidity
xreg_train_full <- cbind(fourier(ts_train, K = c(2, 4)), xreg_train)
xreg_valid_full <- cbind(fourier(ts_train, K = c(2, 4), h = n_valid), xreg_valid)

fit_fourier_weather <- auto.arima(ts_train,
                                  xreg = xreg_train_full,
                                  seasonal = FALSE,
                                  stepwise = FALSE,
                                  approximation = FALSE)

forecast_fourier_weather <- forecast(fit_fourier_weather,
                                     xreg = xreg_valid_full,
                                     h = n_valid)

accuracy_weather <- accuracy(forecast_fourier_weather, ts_valid)
print(accuracy_weather)

# Plot: Fourier + ARIMA + Temp/Humidity
autoplot(forecast_fourier_weather) +
  autolayer(ts_valid, series = "Actual") +
  labs(title = "Fourier + ARIMA + Temp/Humid",
       x = "Date", y = "Demand") +
  theme_bw()

```

8.Average of the best models
```{r}
# Fourier+ARIMA + TBATS + NNETAR
ensemble_mean <- (forecast_fourier$mean + 
                  forecast_tbats$mean + 
                  forecast_nnetar$mean) / 3

accuracy_ensemble <- accuracy(ensemble_mean, ts_valid)
print(accuracy_ensemble)

# Modeling
fourier_full <- fourier(ts_load, K = c(2, 4))
fourier_future <- fourier(ts_load, K = c(2, 4), h = 31)

fit_fourier_full <- auto.arima(ts_load,
                               xreg = fourier_full,
                               seasonal = FALSE,
                               stepwise = FALSE,
                               approximation = FALSE)

fit_tbats_full <- tbats(ts_load)
fit_nnetar_full <- nnetar(ts_load, P = 1, repeats = 20)

# Forecast
fc_fourier_full <- forecast(fit_fourier_full, xreg = fourier_future, h = 31)
fc_tbats_full   <- forecast(fit_tbats_full, h = 31)
fc_nnetar_full  <- forecast(fit_nnetar_full, h = 31)

# Ensemble Average
ensemble_final <- (fc_fourier_full$mean + 
                   fc_tbats_full$mean + 
                   fc_nnetar_full$mean) / 3


```

9. Weighted Average of Tbats and Fourier
--> Turned out this is not the best
```{r}
weights3 <- list(
  c(0.2, 0.8),
  c(0.1, 0.9),
  c(0.0, 1.0)
)

for (w in weights3) {
  ens <- w[1] * forecast_tbats$mean + w[2] * forecast_fourier$mean
  mape <- accuracy(ens, ts_valid)["Test set", "MAPE"]
  cat("TBATS:", w[1], "| Fourier:", w[2], "| MAPE:", round(mape, 4), "\n")
}
```

Submission
```{r}
# Third Submission
dates_july2011 <- seq(as.Date("2011-07-01"), 
                      as.Date("2011-07-31"), 
                      by = "day")

submission <- data.frame(
  date = dates_july2011,
  load = as.numeric(forecast_final$mean)
)

print(submission)

# CSV
write.csv(submission, 
          "Kim_Huang_ThirdSubmission.csv", 
          row.names = FALSE)


# Fourth Submission
dates_july2011 <- seq(as.Date("2011-07-01"), 
                      as.Date("2011-07-31"), 
                      by = "day")

submission <- data.frame(
  date = dates_july2011,
  load = as.numeric(ensemble_final)
)

print(submission)
write.csv(submission, "Kim_Huang_FourthSubmission.csv", row.names = FALSE)


# Fifth Submission
dates_july2011 <- seq(as.Date("2011-07-01"), 
                      as.Date("2011-07-31"), 
                      by = "day")

submission_tbats <- data.frame(
  date = dates_july2011,
  load = as.numeric(fc_tbats_full$mean)
)

write.csv(submission_tbats, "Kim_Huang_FifthSubmission.csv", row.names = FALSE)

# Sixth Submission
ensemble_best <- 0.3 * fc_tbats_full$mean + 0.7 * fc_fourier_full$mean

submission_weighted <- data.frame(
  date = dates_july2011,
  load = as.numeric(ensemble_best)
)

write.csv(submission_weighted, "Kim_Huang_SixthSubmission.csv", row.names = FALSE)
```






